version: "3.8"

services:
  makeapiback:
    container_name: make-api-back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3077:3000"
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
