[functions]
  node_bundler = "esbuild"
  ignored_node_modules = [
    "@nestjs/websockets",
    "@nestjs/microservices"
  ]

# "/api" exato → encaminha para "/.netlify/functions/nest/api"
[[redirects]]
  from = "/api"
  to = "/.netlify/functions/nest/api"
  status = 200

# "/api/*" → mantém o prefixo dentro da Function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nest/api/:splat"
  status = 200
